spring.application.name=webchat-cloud
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d7knqjegvqtc7382uq90-a.singapore-postgres.render.com/webchat_db_o1hk}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:webchat_db_o1hk_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:6J4ZqPJzxhU2OzyFoEEbCyXru3e2KjW1}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
